### ISSUE TITLE
fail to execute any command on SBCL 2.0.3

### ISSUE THREAD

**Issue by ailisp** [koji-kojiro/cl-repl#50] opened 2020-05-03 04:43 UTC
in ros-repl or cl-repl, type 3 <Enter> get this output:
```
➜  ~ ros-repl
cl-repl 0.6.4 on Roswell 19.08.10.101, SBCL 2.0.3
(C) 2017-2018 TANI Kojiro <kojiro0531@gmail.com>

CL-USER> 3CORRUPTION WARNING in SBCL pid 24201(tid 0x7fe7cd4ee740):
Memory fault at (nil) (pc=0x7fe7ccfeccc0, fp=0x7fe7cd00ecc0, sp=0x7fe7cd236770) tid 0x7fe7cd4ee740
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
Unhandled memory fault at #x0.
 [Condition of type MEMORY-FAULT-ERROR]

Restarts:
 0: [*ABORT] Deduce debugger level.
 1: [*EXIT] Exit CL-REPL.
 2: [*RETRY] Try evaluating again.

Backtrace:
 0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000000))
 1: ("foreign function: call_into_lisp")
 --more--

Usage:
  Ctrl+r: select restart. Ctrl+t: show backtrace.

[1]CL-USER> 
```
My system:
```
  Operating System: Ubuntu 19.04
            Kernel: Linux 5.0.0-38-generic
      Architecture: x86-64
```

**Comment by maxwellgisborne** [comment] 2020-06-14 12:47
I have this same problem, result of evaluating (+ 1 2) bellow

```
CL-USER> (+ 1 2)CORRUPTION WARNING in SBCL pid 86838(tid 0x7f36c19892c0):
Memory fault at (nil) (pc=0x7f36c148df31, fp=0x7f36c14b0960, sp=0x7f36c16d67c0) tid 0x7f36c19892c0
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
Unhandled memory fault at #x0.
 [Condition of type MEMORY-FAULT-ERROR]

Restarts:
 0: [*ABORT] Deduce debugger level.
 1: [*EXIT] Exit CL-REPL.
 2: [*RETRY] Try evaluating again.

Backtrace:
 0: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000000))
 1: ("foreign function: call_into_lisp")
 --more--

Usage:
  Ctrl+r: select restart. Ctrl+t: show backtrace.

[1]CL-USER> 

```
My system:
```
Operating System: Arch Linux
Kernel: Linux 5.7.2-arch1-1
Architecture: x86-64
```

**Comment by ohmree** [comment] 2020-09-10 12:40
Same here, using SBCL 2.0.8 compiled using Roswell.

**Comment by hellerve** [comment] 2020-10-14 19:02
I believe this is a duplicate of #44.

**Comment by ryukinix** [comment] 2020-10-18 16:51
One solution: https://github.com/koji-kojiro/cl-repl/pull/51

**Closed as completed** 2020-10-21 03:39 UTC
